### ISSUE TITLE
Base64 Handling

### ISSUE THREAD

**Issue by amanuel2** [amanuel2/ng-forum#14]
As you can see, i currently just store the Base64 Into the Database manually. 

https://github.com/amanuel2/ng-forum/blob/master/services/encodeImageToBase64.js

Well, i thought about that, because i saw it in effect when it significantly reduced performance, and kills the database. Well then i thought about the Imgur API, to change it to Url which wont be that hard, but then Imgur is disabled in School Computers. So is there any alternative to Imgur? Tinypic Maybe?

**Comment by napestershine** [comment]
What is goal ?

**Comment by amanuel2** [comment]
@napestershine Much More Increase in Performance!

**Comment by jdc20181** [comment]
Any  progress on this?

**Comment by amanuel2** [comment]
Not yet :( will work on it.. @jdc20181

**Comment by amanuel2** [comment]
Not as important now, since Image Paths, are not part of any Parameter on this Forum. But still is important since loading images , would take a long time. Not particularly sure on Imgur since its blocked on most school sites @napestershine @jdc20181 , but we will have to make some adjustments on this. Thankyou for your cooperation.

**Comment by jdc20181** [comment]
One thing I will mention @amanuel2  is that images that are not located on site, and have to be pulled from another server takes longer. So if you ever do need to use images add them directly as a file. 

And that is also true about it being blocked at school. That is why we need to relook at the meta tags, as my old school filter went by those tags (it had other ways also but this is the most general way)

The images would be shown as "Content blocked by Filter" instead of the image if used from a external site that was blocked. 

As far as the speed. Cache is  what we need to focus on. Google reccomends to use cache so it doesn't need to pull the same data from the server and stores it local instead. And Yes we can apply updates, all we have to do is set a expiration date (not like mm/dd/yyyy) but like like this:  

'Cache-control: max-age = seconds (e.g. 86400 seconds is 24 hours)'

@amanuel2 I will discuss this more in depth later with you, and nasr :+1:

**Comment by amanuel2** [comment]
@jdc20181 back from school btw. Um, im not tottaly sure on passing by the meta tags... My school did a preety good job of blocking Imgur. The only way i could pass it is by changing my DNS Server im preety sure? But its an extension. As far as speed goes, it is not going to well, as Yes Guys i have added a Loading Stage which will be feautured at the next Update.

Thanks for your response @jdc20181

**Comment by jdc20181** [comment]
Your welcome :)

**Comment by amanuel2** [comment]
Blobs, not working for a period of time. Meaning it works for now, but later it wont render propery

**Comment by amanuel2** [comment]
Turns out, Base64 Are Faster. Since they are strings, they are much faster than HTTP(S).
