### ISSUE TITLE
What happened to ng-forum.site88.net?

### ISSUE THREAD

**Issue by onlineth** [amanuel2/ng-forum#40]
How am I going to meet Developers around the Globe? I don't think http://error404.000webhost.com/ can help me.

**Comment by jdc20181** [comment]
This project is currently on hold it was actually designed to be usable by
anyone. On your own website of course. Due to inactivity I assume the
hosting was cancelled because it was a free based hosting. If you wish to
use it you will have to fork and look through the code yourself.

Thanks for being interested!

**Comment by onlineth** [comment]
But how do I meet developers around the globe? How will I fill this void in my life?

**Comment by jdc20181** [comment]
There are literally thousands of forums to collaborate.

I do not know how long you have coded but I suggest checking out
FreeCodeCamp that's the most active learning community there is.

Many forums can be found online over a span of hundreds of languages.

You may also try joining or contributing to a project.

Good luck.

**Comment by onlineth** [comment]
(I was being unbelievably sarcastic, but thank you:D)

**Comment by amanuel2** [comment]
@onlineth tom, stop troling my other projects lol..  get back to BoneOS. Jeff is just a bot, useless machine

**Comment by jdc20181** [comment]
lol aman. Not a bot when I get a notification at almost 10pm at night-
about a dead project. I answer it lol.

**Comment by amanuel2** [comment]
@jdc20181 bot-stop.
